server:
  port: 8888
spring:
  application:
     name: admin-server
  boot:
    admin:
      client:
        url: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
    file: ./log/log.log
    level:
         root: info
