server:
  port: 8080
  servlet:
    context-path: /SpringbootRabbitMQ
spring:
  rabbitmq:
    connection-timeout: 15000  #超时时间
    addresses: 39.106.136.45:5672  #多个以逗号分隔
    password: guest
    username: guest
    listener:
      simple:
        prefetch: 1                 # 每个线程每次消费一条数据，防止mq 数据过多时，造成web应用宕机
        concurrency: 2              # 指定最小的消费者数量
        max-concurrency: 10         # 指定最大的消费者数量
        acknowledge-mode: auto      # 消息确认方式  若改为 manual 需要手动确认消息