server:
  port: 8080
  servlet:
    context-path: /SpringBootUFLO2
spring:
  datasource:
     url: jdbc:mysql://39.106.136.45:3306/webchat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
     username: root
     password: 492168579@qq.com
     driver-class-name: com.mysql.cj.jdbc.Driver
     hikari: 
       maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上 
       maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)  jpa:
    database: MYSQL
    show-sql: true
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.yzy.could: debug

 